"""LLM trade analyst — an advisory veto sidecar, never a signal source.

Design (per 2026 best practice, e.g. the TradingAgents pattern): the LLM
reviews a proposed trade with compact market context and may veto it.
Blocking bad trades needs less precision than picking good ones, so this
is the one place an LLM adds value safely. It is:

  - optional (disabled by default),
  - strictly time-boxed (a slow model cannot stall the trading loop),
  - fail-open (if the LLM is unreachable the quantitative decision stands),
  - subordinate to the risk engine (it can only veto, never force a trade).

Providers: local Ollama (default, keeps market activity private) or the
Anthropic API (set ANTHROPIC_API_KEY).
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
from dataclasses import dataclass
from typing import Dict, Optional

import pandas as pd

from ..indicators import ta
from ..models import Signal

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = (
    "You are a risk-focused trading analyst reviewing a proposed spot trade "
    "generated by a quantitative system. Your only job is to catch clearly "
    "bad entries: exhaustion chasing, entries straight into obvious "
    "resistance, buying a knife mid-crash, or context the numbers imply but "
    "the strategy ignores. You cannot initiate trades. Respond with ONLY a "
    'JSON object: {"verdict": "approve" | "veto", "confidence": <0..1>, '
    '"reasoning": "<one sentence>"}. Approve unless something is clearly '
    "wrong — a weak or uncertain objection is an approve."
)


@dataclass
class AnalystVerdict:
    verdict: str  # "approve" | "veto" | "unavailable"
    confidence: float
    reasoning: str

    @property
    def is_veto(self) -> bool:
        return self.verdict == "veto"


class LLMAnalyst:
    def __init__(self, config: Optional[Dict] = None):
        cfg = dict(config or {})
        self.enabled = bool(cfg.get("enabled", False))
        self.provider = cfg.get("provider", "ollama")
        self.model = cfg.get("model", "gemma4:latest")
        self.ollama_url = cfg.get("ollama_url", "http://localhost:11434")
        self.timeout = float(cfg.get("timeout_seconds", 20.0))
        self.min_veto_confidence = float(cfg.get("min_veto_confidence", 0.6))

    def build_context(self, signal: Signal, df: pd.DataFrame) -> str:
        """Compact, numeric market context — no token waste."""
        close = df["close"]
        rsi_val = ta.rsi(close, 14).iloc[-1]
        atr_val = ta.atr(df["high"], df["low"], close, 14).iloc[-1]
        last = float(close.iloc[-1])
        changes = {
            "1_bar": close.pct_change(1).iloc[-1],
            "6_bars": close.pct_change(6).iloc[-1] if len(close) > 6 else float("nan"),
            "24_bars": (
                close.pct_change(24).iloc[-1] if len(close) > 24 else float("nan")
            ),
        }
        dist_from_high = last / float(close.tail(100).max()) - 1.0
        lines = [
            f"Proposed trade: {signal.action.value.upper()} {signal.symbol}",
            f"Strategy: {signal.strategy}, confidence {signal.confidence:.2f}",
            f"Regime: {signal.regime.value if signal.regime else 'unknown'}",
            f"Price: {last:.6g}",
            f"Stop loss: {signal.stop_loss:.6g}" if signal.stop_loss else "Stop loss: none",
            f"Take profit: {signal.take_profit:.6g}" if signal.take_profit else "Take profit: none",
            "Recent % change: "
            + ", ".join(
                f"{k}: {v * 100:+.2f}%" for k, v in changes.items() if pd.notna(v)
            ),
            f"RSI(14): {rsi_val:.1f}" if pd.notna(rsi_val) else "RSI: n/a",
            (
                f"ATR(14): {atr_val / last * 100:.2f}% of price"
                if pd.notna(atr_val)
                else "ATR: n/a"
            ),
            f"Distance from 100-bar high: {dist_from_high * 100:+.2f}%",
        ]
        return "\n".join(lines)

    async def review(self, signal: Signal, df: pd.DataFrame) -> AnalystVerdict:
        """Review a proposed trade. Never raises; fails open."""
        if not self.enabled:
            return AnalystVerdict("approve", 1.0, "analyst disabled")
        context = self.build_context(signal, df)
        try:
            raw = await asyncio.wait_for(
                self._complete(context), timeout=self.timeout
            )
            verdict = self._parse(raw)
            if verdict.is_veto and verdict.confidence < self.min_veto_confidence:
                return AnalystVerdict(
                    "approve",
                    verdict.confidence,
                    f"veto below confidence bar: {verdict.reasoning}",
                )
            return verdict
        except asyncio.TimeoutError:
            logger.warning("LLM analyst timed out after %.0fs — failing open", self.timeout)
            return AnalystVerdict("unavailable", 0.0, "timeout")
        except Exception as exc:  # noqa: BLE001 - advisory layer must not break trading
            logger.warning("LLM analyst error (failing open): %s", exc)
            return AnalystVerdict("unavailable", 0.0, str(exc))

    async def _complete(self, context: str) -> str:
        if self.provider == "anthropic":
            return await self._complete_anthropic(context)
        return await self._complete_ollama(context)

    async def _complete_ollama(self, context: str) -> str:
        import aiohttp

        payload = {
            "model": self.model,
            "system": SYSTEM_PROMPT,
            "prompt": context,
            "stream": False,
            # Thinking models (gemma4, qwen3, ...) spend tokens on internal
            # reasoning before the visible answer — a tight cap yields an
            # empty response with done_reason=length. Budget generously; the
            # wall-clock timeout is the real guard.
            "options": {"temperature": 0.1, "num_predict": 2048},
        }
        timeout = aiohttp.ClientTimeout(total=self.timeout)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.post(
                f"{self.ollama_url}/api/generate", json=payload
            ) as resp:
                if resp.status != 200:
                    raise RuntimeError(f"Ollama HTTP {resp.status}")
                data = await resp.json()
                return data.get("response", "")

    async def _complete_anthropic(self, context: str) -> str:
        import aiohttp

        api_key = os.getenv("ANTHROPIC_API_KEY")
        if not api_key:
            raise RuntimeError("ANTHROPIC_API_KEY not set")
        payload = {
            "model": self.model if "claude" in self.model else "claude-haiku-4-5-20251001",
            "max_tokens": 200,
            "system": SYSTEM_PROMPT,
            "messages": [{"role": "user", "content": context}],
        }
        headers = {
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
        timeout = aiohttp.ClientTimeout(total=self.timeout)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.post(
                "https://api.anthropic.com/v1/messages",
                json=payload,
                headers=headers,
            ) as resp:
                if resp.status != 200:
                    body = await resp.text()
                    raise RuntimeError(f"Anthropic API {resp.status}: {body[:200]}")
                data = await resp.json()
                return "".join(
                    block.get("text", "") for block in data.get("content", [])
                )

    @staticmethod
    def _parse(raw: str) -> AnalystVerdict:
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if not match:
            raise ValueError(f"no JSON in LLM response: {raw[:120]!r}")
        data = json.loads(match.group(0))
        verdict = str(data.get("verdict", "approve")).lower()
        if verdict not in ("approve", "veto"):
            verdict = "approve"
        return AnalystVerdict(
            verdict=verdict,
            confidence=float(data.get("confidence", 0.5)),
            reasoning=str(data.get("reasoning", ""))[:300],
        )
